-- Match local -> cloud full sync
-- Generated at 2026-09-18T02:33:27.402Z
CREATE DATABASE IF NOT EXISTS `match` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `match`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

DROP VIEW IF EXISTS `family_profiles_view`;
DROP VIEW IF EXISTS `family_trial_feedback_view`;
DROP VIEW IF EXISTS `mentor_profiles_view`;
DROP VIEW IF EXISTS `mentor_trial_feedback_view`;
DROP TABLE IF EXISTS `family_daily_feedback`;
DROP TABLE IF EXISTS `family_trial_feedback`;
DROP TABLE IF EXISTS `mentor_daily_feedback`;
DROP TABLE IF EXISTS `mentor_trial_feedback`;
DROP TABLE IF EXISTS `role_bindings`;
DROP TABLE IF EXISTS `trial_records`;
DROP TABLE IF EXISTS `users`;

-- 表 family_daily_feedback
CREATE TABLE `family_daily_feedback` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trial_record_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `card_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `target_subtitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `class_date` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `class_duration` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `satisfaction_points_json` json NOT NULL,
  `satisfaction_point_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `objective_unsatisfied_json` json NOT NULL,
  `objective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `subjective_unsatisfied_json` json NOT NULL,
  `subjective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status_after_feedback` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `feedback_json` json NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_family_daily_openid` (`openid`),
  KEY `idx_family_daily_card_id` (`card_id`),
  KEY `idx_family_daily_updated` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `family_daily_feedback` (`id`, `openid`, `trial_record_id`, `card_id`, `target_title`, `target_subtitle`, `class_date`, `class_duration`, `satisfaction_points_json`, `satisfaction_point_other`, `objective_unsatisfied_json`, `objective_unsatisfied_other`, `subjective_unsatisfied_json`, `subjective_unsatisfied_other`, `continue_choice`, `continue_choice_other`, `status_after_feedback`, `feedback_json`, `created_at`, `updated_at`) VALUES
('daily-family-1789659315359-uyoon7', 'dev-openid-seed-family-02', 'trial-1789656467505-1cmbl4', 'mentor-dev-openid-client-1784996196015-qec9q95u', '真机调试账号', '四川大学 · s', '2026-09-17', '45', '[\"孩子愿意配合、有互动\"]', '', '[\"网络或上课条件不理想\"]', '', '[\"我这边配合不够及时\"]', '', '不愿意', '', 'terminated', '{\"classDate\":\"2026-09-17\",\"classDuration\":\"45\",\"continueChoice\":\"不愿意\",\"satisfactionPoints\":[\"孩子愿意配合、有互动\"],\"continueChoiceOther\":\"\",\"objectiveUnsatisfied\":[\"网络或上课条件不理想\"],\"subjectiveUnsatisfied\":[\"我这边配合不够及时\"],\"satisfactionPointOther\":\"\",\"objectiveUnsatisfiedOther\":\"\",\"subjectiveUnsatisfiedOther\":\"\"}', '2026-09-17 15:35:15.000', '2026-09-17 15:35:15.000');

-- 表 family_trial_feedback
CREATE TABLE `family_trial_feedback` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trial_record_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `card_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `target_subtitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `trial_date` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `trial_duration` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `satisfaction_points_json` json NOT NULL,
  `satisfaction_point_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `objective_unsatisfied_json` json NOT NULL,
  `objective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `subjective_unsatisfied_json` json NOT NULL,
  `subjective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status_after_feedback` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `feedback_json` json NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_family_feedback_openid` (`openid`),
  KEY `idx_family_feedback_card_id` (`card_id`),
  KEY `idx_family_feedback_updated` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `family_trial_feedback` (`id`, `openid`, `trial_record_id`, `card_id`, `target_title`, `target_subtitle`, `trial_date`, `trial_duration`, `satisfaction_points_json`, `satisfaction_point_other`, `objective_unsatisfied_json`, `objective_unsatisfied_other`, `subjective_unsatisfied_json`, `subjective_unsatisfied_other`, `continue_choice`, `continue_choice_other`, `status_after_feedback`, `feedback_json`, `created_at`, `updated_at`) VALUES
('family-feedback-1789659251160-zcwjao', 'dev-openid-seed-family-07', 'trial-1789659197745-2zvc4b', 'mentor-dev-openid-client-1785042113258-iqyi6n5p', '真实测试', '四川大学 · 人工智能', '2026-09-17', '45', '[\"耐心负责，沟通自然\",\"讲解清晰，容易理解\"]', '', '[\"内容难度与孩子当前情况不匹配\",\"互动方式还需要调整\"]', '', '[\"孩子当天状态一般，影响了试课效果\",\"我这边课前准备还不够充分\"]', '', '愿意', '', 'pending', '{\"trialDate\":\"2026-09-17\",\"trialDuration\":\"45\",\"continueChoice\":\"愿意\",\"satisfactionPoints\":[\"耐心负责，沟通自然\",\"讲解清晰，容易理解\"],\"continueChoiceOther\":\"\",\"objectiveUnsatisfied\":[\"内容难度与孩子当前情况不匹配\",\"互动方式还需要调整\"],\"subjectiveUnsatisfied\":[\"孩子当天状态一般，影响了试课效果\",\"我这边课前准备还不够充分\"],\"satisfactionPointOther\":\"\",\"objectiveUnsatisfiedOther\":\"\",\"subjectiveUnsatisfiedOther\":\"\"}', '2026-09-17 15:34:11.000', '2026-09-17 15:34:11.000');

-- 表 mentor_daily_feedback
CREATE TABLE `mentor_daily_feedback` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trial_record_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `card_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `target_subtitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `class_date` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `class_duration` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `satisfaction_points_json` json NOT NULL,
  `satisfaction_point_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `objective_unsatisfied_json` json NOT NULL,
  `objective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `subjective_unsatisfied_json` json NOT NULL,
  `subjective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status_after_feedback` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `feedback_json` json NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mentor_daily_openid` (`openid`),
  KEY `idx_mentor_daily_card_id` (`card_id`),
  KEY `idx_mentor_daily_updated` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 表 mentor_trial_feedback
CREATE TABLE `mentor_trial_feedback` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trial_record_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `card_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `target_subtitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `trial_date` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `trial_duration` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `satisfaction_points_json` json NOT NULL,
  `satisfaction_point_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `objective_unsatisfied_json` json NOT NULL,
  `objective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `subjective_unsatisfied_json` json NOT NULL,
  `subjective_unsatisfied_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `continue_choice_other` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status_after_feedback` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `feedback_json` json NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mentor_feedback_openid` (`openid`),
  KEY `idx_mentor_feedback_card_id` (`card_id`),
  KEY `idx_mentor_feedback_updated` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `mentor_trial_feedback` (`id`, `openid`, `trial_record_id`, `card_id`, `target_title`, `target_subtitle`, `trial_date`, `trial_duration`, `satisfaction_points_json`, `satisfaction_point_other`, `objective_unsatisfied_json`, `objective_unsatisfied_other`, `subjective_unsatisfied_json`, `subjective_unsatisfied_other`, `continue_choice`, `continue_choice_other`, `status_after_feedback`, `feedback_json`, `created_at`, `updated_at`) VALUES
('mentor-feedback-1789659222957-9r86xg', 'dev-openid-client-1785042113258-iqyi6n5p', 'trial-1789659197745', 'family-dev-openid-seed-family-07', '严一一', '四川省成都市高新区', '2026-09-17', '45', '[\"态度积极，愿意配合\"]', '', '[\"注意力不集中，容易走神\"]', '', '[\"我未能有效调动学生积极性\"]', '', '需要调整后再试一次', '', 'pending', '{\"trialDate\":\"2026-09-17\",\"trialDuration\":\"45\",\"continueChoice\":\"需要调整后再试一次\",\"satisfactionPoints\":[\"态度积极，愿意配合\"],\"continueChoiceOther\":\"\",\"objectiveUnsatisfied\":[\"注意力不集中，容易走神\"],\"subjectiveUnsatisfied\":[\"我未能有效调动学生积极性\"],\"satisfactionPointOther\":\"\",\"objectiveUnsatisfiedOther\":\"\",\"subjectiveUnsatisfiedOther\":\"\"}', '2026-09-17 15:33:42.000', '2026-09-17 15:33:42.000');

-- 表 role_bindings
CREATE TABLE `role_bindings` (
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`openid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `role_bindings` (`openid`, `role`, `created_at`, `updated_at`) VALUES
('dev-openid-0e3s4RGa1cDy7M0jdPFa1c8yYM0s4RGY', 'mentor', '2026-07-02 23:17:10.000', '2026-05-19 07:24:06.000'),
('dev-openid-client-1784964290004-sxptt2m8', 'family', '2026-07-02 23:24:52.000', '2026-05-19 07:24:52.000'),
('dev-openid-client-1784996196015-qec9q95u', 'mentor', '2026-09-16 15:57:12.000', '2026-08-27 23:57:12.000'),
('dev-openid-client-1784996428540-q040z9jy', 'mentor', '2026-07-03 08:20:30.000', '2026-05-19 16:20:30.000'),
('dev-openid-client-1784999000363-3j81jb6p', 'family', '2026-07-03 17:03:22.000', '2026-05-20 09:04:16.000'),
('dev-openid-client-1785039365615-hh6memj9', 'mentor', '2026-07-05 12:16:07.000', '2026-05-21 20:16:07.000'),
('dev-openid-client-1785039392408-t1wbg02d', 'family', '2026-07-05 20:16:35.000', '2026-05-22 12:17:33.000'),
('dev-openid-client-1785042113258-iqyi6n5p', 'mentor', '2026-07-07 21:01:56.000', '2026-05-24 13:02:49.000'),
('dev-openid-client-1785042644023-ugs60ojj', 'family', '2026-07-09 13:10:46.000', '2026-05-26 05:11:35.000'),
('dev-openid-client-1785043393047-s0lh0fuj', 'mentor', '2026-07-10 21:23:15.000', '2026-05-27 13:23:43.000'),
('dev-openid-client-1785043845394-5vdletqp', 'family', '2026-07-12 13:30:47.000', '2026-05-29 05:31:18.000'),
('dev-openid-client-1785044661567-j5d1adqh', 'family', '2026-07-13 13:44:23.000', '2026-05-30 05:45:07.000'),
('dev-openid-client-1785044767504-gcg4ir94', 'family', '2026-07-14 21:46:10.000', '2026-05-31 13:46:39.000'),
('dev-openid-client-1789446856463-2m86ckul', 'family', '2026-09-15 04:34:19.000', '2026-08-05 20:34:19.000'),
('dev-openid-client-1789447543956-pp87ehr9', 'mentor', '2026-09-15 04:55:24.000', '2026-08-06 04:55:24.000'),
('dev-openid-client-1789448146952-hmqdpkj8', 'mentor', '2026-09-15 04:55:48.000', '2026-08-06 12:55:48.000'),
('dev-openid-client-1789449585184-gcey804g', 'family', '2026-09-15 05:19:47.000', '2026-08-07 05:20:17.000'),
('dev-openid-client-1789450300455-7ve2svkj', 'mentor', '2026-09-15 05:32:49.000', '2026-08-08 21:33:05.000'),
('dev-openid-client-1789482263819-ey12ipnt', 'mentor', '2026-09-15 14:24:25.000', '2026-08-10 14:24:47.000'),
('dev-openid-client-1789555520303-edvaem93', 'mentor', '2026-09-16 10:45:28.000', '2026-08-15 02:45:28.000'),
('dev-openid-client-1789555540948-sb60ku54', 'mentor', '2026-09-16 10:45:42.000', '2026-08-15 10:45:42.000'),
('dev-openid-client-1789560203315-q4zsvi37', 'mentor', '2026-09-16 12:03:25.000', '2026-08-16 04:04:39.000'),
('dev-openid-client-1789561187784-ddgc4et3', 'mentor', '2026-09-16 12:19:49.000', '2026-08-18 04:19:49.000'),
('dev-openid-client-1789568015099-zfuz1qzy', 'mentor', '2026-09-16 14:13:39.000', '2026-08-24 22:13:39.000'),
('dev-openid-client-1789568031816-omcw53v4', 'mentor', '2026-09-16 14:13:53.000', '2026-08-25 06:13:53.000'),
('dev-openid-client-1789609930556-mhe2lxmc', 'mentor', '2026-09-17 01:52:13.000', '2026-09-01 01:52:13.000'),
('dev-openid-client-1789611560287-rb7n4d5g', 'family', '2026-09-17 02:19:22.000', '2026-09-01 10:19:22.000'),
('dev-openid-client-1789655524875-tsfr2c5m', 'mentor', '2026-09-17 14:32:07.000', '2026-09-07 14:32:07.000'),
('dev-openid-seed-family-01', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-02', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-03', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-04', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-05', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-06', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-07', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-08', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-09', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-10', 'family', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-01', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-02', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-03', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-04', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-05', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-06', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-07', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-08', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-09', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-10', 'mentor', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000');

-- 表 trial_records
CREATE TABLE `trial_records` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `card_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `continue_choice` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `card_data_json` json NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_role_status_updated` (`role`,`status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `trial_records` (`id`, `role`, `card_id`, `status`, `continue_choice`, `card_data_json`, `created_at`, `updated_at`, `openid`) VALUES
('trial-1789652911011', 'mentor', 'family-dev-openid-seed-family-01', 'pending', '', '{\"id\":\"family-dev-openid-seed-family-01\",\"badge\":\"家庭\",\"title\":\"严耀国\",\"details\":[{\"label\":\"孩子姓名\",\"value\":\"严耀国\"},{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"男\"},{\"label\":\"家长称呼\",\"value\":\"蹦蹦妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"小学四年级\"},{\"label\":\"电话号码\",\"value\":\"13980086000\"},{\"label\":\"微信号\",\"value\":\"Jiang2L\"},{\"label\":\"常住区域\",\"value\":\"四川省成都市高新区\"},{\"kind\":\"sort\",\"items\":[\"体育\",\"语文\",\"数学\",\"英语\",\"地理\",\"化学\"],\"label\":\"需要辅导科目\"},{\"kind\":\"sort\",\"items\":[\"学习效率低，容易拖延\",\"对科目缺乏兴趣，动力不足\",\"解题思路不清晰，方法欠缺\",\"基础知识不牢固\",\"其他：华西附二院诊断他有轻微的抽动症\"],\"label\":\"学习困难\"},{\"kind\":\"sort\",\"items\":[\"能帮助孩子建立良好的学习习惯\",\"有耐心，善于鼓励，不轻易发脾气\",\"性格开朗，有亲和力，能调动孩子积极性\",\"讲解清晰有条理，能化繁为简\",\"能洞察孩子学习中的困难点，针对性解决\"],\"label\":\"老师特质\"},{\"kind\":\"sort\",\"items\":[\"启发引导型\",\"鼓励陪伴型\",\"问题向导型\"],\"label\":\"教学风格\"},{\"kind\":\"single\",\"label\":\"辅导侧重点\",\"value\":\"查缺补漏，专项攻克孩子的薄弱环节\"},{\"kind\":\"single\",\"label\":\"关注学习状态\",\"value\":\"可以接受，顺其自然。\"},{\"kind\":\"single\",\"label\":\"沟通期望\",\"value\":\"课后能与我简单沟通本次辅导内容和孩子表现。\"},{\"kind\":\"single\",\"label\":\"项目理解\",\"value\":\"完全理解并认同，相信其专业性。\"},{\"kind\":\"single\",\"label\":\"反馈意愿\",\"value\":\"愿意积极配合。\"},{\"kind\":\"multi\",\"items\":[\"线下\"],\"label\":\"上课方式\"},{\"label\":\"上课频率\",\"value\":\"工作日每天\"},{\"label\":\"过往辅导经历\",\"value\":\"他曾经学过硬笔书法，篮球、游泳、羽毛球，英语，国学古诗词。\"},{\"label\":\"额外备注\",\"value\":\"从2024年张骏老师团队在高新区分享青少年成长问题，就有关注，但那个时候觉得孩子可能年龄还比较小，自认为还没有达到匹配程度，所以也一直在持续关注。\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"男\"},{\"label\":\"家长称呼\",\"value\":\"蹦蹦妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"小学四年级\"},{\"kind\":\"sort\",\"items\":[\"体育\",\"语文\",\"数学\",\"英语\",\"地理\",\"化学\"],\"label\":\"需要辅导科目\"}],\"subtitle\":\"四川省成都市高新区\"}', '2026-09-17 13:48:31.000', '2026-09-14 15:25:58.000', 'dev-openid-seed-mentor-04'),
('trial-1789652911011-sfwhco', 'family', 'mentor-dev-openid-seed-mentor-04', 'pending', '', '{\"id\":\"mentor-dev-openid-seed-mentor-04\",\"badge\":\"普通成员\",\"title\":\"李冀宽\",\"details\":[{\"label\":\"姓名\",\"value\":\"李冀宽\"},{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"single\",\"label\":\"骨干成员\",\"value\":\"否\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"2025\"},{\"label\":\"学校\",\"value\":\"四川大学\"},{\"label\":\"专业\",\"value\":\"基础医学\"},{\"label\":\"学院\",\"value\":\"华西基础医学与法医学院\"},{\"label\":\"微信号\",\"value\":\"wxid_i9qoajhvc2ju12 电话：18225142676\"},{\"kind\":\"sort\",\"items\":[\"英语\",\"生物\",\"数学\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"小学\",\"初中\",\"高中\"],\"label\":\"意向教学年级段\"},{\"kind\":\"multi\",\"items\":[\"结构化引导型\",\"情感支持型\",\"鼓励启发型\",\"灵活应变型\",\"耐心倾听型\"],\"label\":\"风格类型\"},{\"kind\":\"multi\",\"items\":[\"线上\",\"线下\"],\"label\":\"上课方式\"},{\"label\":\"暑假所在地\",\"value\":\"重庆市南川区\"},{\"label\":\"开学后所在地\",\"value\":\"成都市双流区\"},{\"label\":\"上课频率\",\"value\":\"一周一次\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"sort\",\"items\":[\"英语\",\"生物\",\"数学\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"小学\",\"初中\",\"高中\"],\"label\":\"意向教学年级段\"}],\"subtitle\":\"四川大学 · 基础医学\"}', '2026-09-17 13:48:31.000', '2026-09-14 15:25:58.000', 'dev-openid-seed-family-01'),
('trial-1789652911440', 'mentor', 'family-dev-openid-seed-family-02', 'rejected', '', '{\"id\":\"family-dev-openid-seed-family-02\",\"badge\":\"家庭\",\"title\":\"黄斯燕\",\"details\":[{\"label\":\"孩子姓名\",\"value\":\"黄斯燕\"},{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"谢阿姨\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"高二\"},{\"label\":\"电话号码\",\"value\":\"19950718717\"},{\"label\":\"微信号\",\"value\":\"innay2025\"},{\"label\":\"常住区域\",\"value\":\"四川省宜宾市\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"语文\",\"英语\"],\"label\":\"需要辅导科目\"},{\"kind\":\"sort\",\"items\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\"],\"label\":\"学习困难\"},{\"kind\":\"sort\",\"items\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"有耐心，善于鼓励，不轻易发脾气\",\"能洞察孩子学习中的困难点，针对性解决\"],\"label\":\"老师特质\"},{\"kind\":\"sort\",\"items\":[\"鼓励陪伴型\"],\"label\":\"教学风格\"},{\"kind\":\"single\",\"label\":\"辅导侧重点\",\"value\":\"讲解基础知识和重要知识点，并进行巩固拔高\"},{\"kind\":\"single\",\"label\":\"关注学习状态\",\"value\":\"非常希望，这有助于提高学习效率。\"},{\"kind\":\"single\",\"label\":\"沟通期望\",\"value\":\"课后能与我简单沟通本次辅导内容和孩子表现。\"},{\"kind\":\"single\",\"label\":\"项目理解\",\"value\":\"基本了解，愿意尝试。\"},{\"kind\":\"single\",\"label\":\"反馈意愿\",\"value\":\"愿意积极配合。\"},{\"kind\":\"multi\",\"items\":[\"线上\",\"线下\"],\"label\":\"上课方式\"},{\"label\":\"上课频率\",\"value\":\"一周1-2次，以后可以根据孩子意愿增加\"},{\"label\":\"过往辅导经历\",\"value\":\"参加过课外辅导，坚持了的效果还可以\"},{\"label\":\"额外备注\",\"value\":\"在现实世界给孩子找一个陪伴和榜样，提升孩子积极心态、学习兴趣和学习能力，拓展视野\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"谢阿姨\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"高二\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"语文\",\"英语\"],\"label\":\"需要辅导科目\"}],\"subtitle\":\"四川省宜宾市\"}', '2026-09-17 13:48:31.000', '2026-09-12 23:16:25.000', 'dev-openid-seed-mentor-04'),
('trial-1789652911440-pgqfz0', 'family', 'mentor-dev-openid-seed-mentor-04', 'rejected', '不愿意', '{\"id\":\"mentor-dev-openid-seed-mentor-04\",\"badge\":\"普通成员\",\"title\":\"李冀宽\",\"details\":[{\"label\":\"姓名\",\"value\":\"李冀宽\"},{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"single\",\"label\":\"骨干成员\",\"value\":\"否\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"2025\"},{\"label\":\"学校\",\"value\":\"四川大学\"},{\"label\":\"专业\",\"value\":\"基础医学\"},{\"label\":\"学院\",\"value\":\"华西基础医学与法医学院\"},{\"label\":\"微信号\",\"value\":\"wxid_i9qoajhvc2ju12 电话：18225142676\"},{\"kind\":\"sort\",\"items\":[\"英语\",\"生物\",\"数学\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"小学\",\"初中\",\"高中\"],\"label\":\"意向教学年级段\"},{\"kind\":\"multi\",\"items\":[\"结构化引导型\",\"情感支持型\",\"鼓励启发型\",\"灵活应变型\",\"耐心倾听型\"],\"label\":\"风格类型\"},{\"kind\":\"multi\",\"items\":[\"线上\",\"线下\"],\"label\":\"上课方式\"},{\"label\":\"暑假所在地\",\"value\":\"重庆市南川区\"},{\"label\":\"开学后所在地\",\"value\":\"成都市双流区\"},{\"label\":\"上课频率\",\"value\":\"一周一次\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"sort\",\"items\":[\"英语\",\"生物\",\"数学\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"小学\",\"初中\",\"高中\"],\"label\":\"意向教学年级段\"}],\"subtitle\":\"四川大学 · 基础医学\"}', '2026-09-17 13:48:31.000', '2026-09-12 23:16:25.000', 'dev-openid-seed-family-02'),
('trial-1789652911817', 'mentor', 'family-dev-openid-seed-family-03', 'pending', '', '{\"id\":\"family-dev-openid-seed-family-03\",\"badge\":\"家庭\",\"title\":\"七七\",\"details\":[{\"label\":\"孩子姓名\",\"value\":\"七七\"},{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"七七妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"初一\"},{\"label\":\"电话号码\",\"value\":\"18982812939\"},{\"label\":\"微信号\",\"value\":\"18982812939\"},{\"label\":\"常住区域\",\"value\":\"四川达州大竹\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\"],\"label\":\"需要辅导科目\"},{\"kind\":\"sort\",\"items\":[\"考试时容易紧张，发挥失常\",\"解题思路不清晰，方法欠缺\",\"学习效率低，容易拖延\"],\"label\":\"学习困难\"},{\"kind\":\"sort\",\"items\":[\"有耐心，善于鼓励，不轻易发脾气\",\"能帮助孩子建立良好的学习习惯\",\"性格开朗，有亲和力，能调动孩子积极性\",\"能洞察孩子学习中的困难点，针对性解决\",\"讲解清晰有条理，能化繁为简\"],\"label\":\"老师特质\"},{\"kind\":\"sort\",\"items\":[\"鼓励陪伴型\",\"启发引导型\"],\"label\":\"教学风格\"},{\"kind\":\"single\",\"label\":\"辅导侧重点\",\"value\":\"怀疑自己的学习能力，已经处于习得性无助状态。需要先建立她对学习的信心和兴趣。\"},{\"kind\":\"single\",\"label\":\"关注学习状态\",\"value\":\"非常希望，这有助于提高学习效率。\"},{\"kind\":\"single\",\"label\":\"沟通期望\",\"value\":\"定期（如每周/每月）有一次详细沟通。\"},{\"kind\":\"single\",\"label\":\"项目理解\",\"value\":\"基本了解，愿意尝试。\"},{\"kind\":\"single\",\"label\":\"反馈意愿\",\"value\":\"愿意积极配合。\"},{\"kind\":\"multi\",\"items\":[\"线上\"],\"label\":\"上课方式\"},{\"label\":\"上课频率\",\"value\":\"老师根据孩子状态来安排\"},{\"label\":\"过往辅导经历\",\"value\":\"有参加过其他补习，但是学过就忘\"},{\"label\":\"额外备注\",\"value\":\"项目对老师的工作怎么进行监管？\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"七七妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"初一\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\"],\"label\":\"需要辅导科目\"}],\"subtitle\":\"四川达州大竹\"}', '2026-09-17 13:48:31.000', '2026-09-15 23:26:44.000', 'dev-openid-seed-mentor-04'),
('trial-1789652911817-x8huv7', 'family', 'mentor-dev-openid-seed-mentor-04', 'pending', '', '{\"id\":\"mentor-dev-openid-seed-mentor-04\",\"badge\":\"普通成员\",\"title\":\"李冀宽\",\"details\":[{\"label\":\"姓名\",\"value\":\"李冀宽\"},{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"single\",\"label\":\"骨干成员\",\"value\":\"否\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"2025\"},{\"label\":\"学校\",\"value\":\"四川大学\"},{\"label\":\"专业\",\"value\":\"基础医学\"},{\"label\":\"学院\",\"value\":\"华西基础医学与法医学院\"},{\"label\":\"微信号\",\"value\":\"wxid_i9qoajhvc2ju12 电话：18225142676\"},{\"kind\":\"sort\",\"items\":[\"英语\",\"生物\",\"数学\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"小学\",\"初中\",\"高中\"],\"label\":\"意向教学年级段\"},{\"kind\":\"multi\",\"items\":[\"结构化引导型\",\"情感支持型\",\"鼓励启发型\",\"灵活应变型\",\"耐心倾听型\"],\"label\":\"风格类型\"},{\"kind\":\"multi\",\"items\":[\"线上\",\"线下\"],\"label\":\"上课方式\"},{\"label\":\"暑假所在地\",\"value\":\"重庆市南川区\"},{\"label\":\"开学后所在地\",\"value\":\"成都市双流区\"},{\"label\":\"上课频率\",\"value\":\"一周一次\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"sort\",\"items\":[\"英语\",\"生物\",\"数学\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"小学\",\"初中\",\"高中\"],\"label\":\"意向教学年级段\"}],\"subtitle\":\"四川大学 · 基础医学\"}', '2026-09-17 13:48:31.000', '2026-09-15 23:26:44.000', 'dev-openid-seed-family-03'),
('trial-1789656467186', 'mentor', 'family-dev-openid-seed-family-01', 'pending', '', '{\"id\":\"family-dev-openid-seed-family-01\",\"badge\":\"家庭\",\"title\":\"严耀国\",\"details\":[{\"label\":\"孩子姓名\",\"value\":\"严耀国\"},{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"男\"},{\"label\":\"家长称呼\",\"value\":\"蹦蹦妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"小学四年级\"},{\"label\":\"电话号码\",\"value\":\"13980086000\"},{\"label\":\"微信号\",\"value\":\"Jiang2L\"},{\"label\":\"常住区域\",\"value\":\"四川省成都市高新区\"},{\"kind\":\"sort\",\"items\":[\"体育\",\"语文\",\"数学\",\"英语\",\"地理\",\"化学\"],\"label\":\"需要辅导科目\"},{\"kind\":\"sort\",\"items\":[\"学习效率低，容易拖延\",\"对科目缺乏兴趣，动力不足\",\"解题思路不清晰，方法欠缺\",\"基础知识不牢固\",\"其他：华西附二院诊断他有轻微的抽动症\"],\"label\":\"学习困难\"},{\"kind\":\"sort\",\"items\":[\"能帮助孩子建立良好的学习习惯\",\"有耐心，善于鼓励，不轻易发脾气\",\"性格开朗，有亲和力，能调动孩子积极性\",\"讲解清晰有条理，能化繁为简\",\"能洞察孩子学习中的困难点，针对性解决\"],\"label\":\"老师特质\"},{\"kind\":\"sort\",\"items\":[\"启发引导型\",\"鼓励陪伴型\",\"问题向导型\"],\"label\":\"教学风格\"},{\"kind\":\"single\",\"label\":\"辅导侧重点\",\"value\":\"查缺补漏，专项攻克孩子的薄弱环节\"},{\"kind\":\"single\",\"label\":\"关注学习状态\",\"value\":\"可以接受，顺其自然。\"},{\"kind\":\"single\",\"label\":\"沟通期望\",\"value\":\"课后能与我简单沟通本次辅导内容和孩子表现。\"},{\"kind\":\"single\",\"label\":\"项目理解\",\"value\":\"完全理解并认同，相信其专业性。\"},{\"kind\":\"single\",\"label\":\"反馈意愿\",\"value\":\"愿意积极配合。\"},{\"kind\":\"multi\",\"items\":[\"线下\"],\"label\":\"上课方式\"},{\"label\":\"上课频率\",\"value\":\"工作日每天\"},{\"label\":\"过往辅导经历\",\"value\":\"他曾经学过硬笔书法，篮球、游泳、羽毛球，英语，国学古诗词。\"},{\"label\":\"额外备注\",\"value\":\"从2024年张骏老师团队在高新区分享青少年成长问题，就有关注，但那个时候觉得孩子可能年龄还比较小，自认为还没有达到匹配程度，所以也一直在持续关注。\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"男\"},{\"label\":\"家长称呼\",\"value\":\"蹦蹦妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"小学四年级\"},{\"kind\":\"sort\",\"items\":[\"体育\",\"语文\",\"数学\",\"英语\",\"地理\",\"化学\"],\"label\":\"需要辅导科目\"}],\"subtitle\":\"四川省成都市高新区\"}', '2026-09-17 14:47:47.000', '2026-09-15 07:26:29.000', 'dev-openid-client-1784996196015-qec9q95u'),
('trial-1789656467186-g7ya7n', 'family', 'mentor-dev-openid-client-1784996196015-qec9q95u', 'pending', '', '{\"id\":\"mentor-dev-openid-client-1784996196015-qec9q95u\",\"badge\":\"普通成员\",\"title\":\"真机调试账号\",\"details\":[{\"label\":\"姓名\",\"value\":\"真机调试账号\"},{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"否\"},{\"kind\":\"single\",\"label\":\"骨干成员\",\"value\":\"否\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"大二\"},{\"label\":\"学校\",\"value\":\"四川大学\"},{\"label\":\"专业\",\"value\":\"s\"},{\"label\":\"学院\",\"value\":\"s\"},{\"label\":\"微信号\",\"value\":\"s\"},{\"kind\":\"sort\",\"items\":[\"语文\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"},{\"kind\":\"multi\",\"items\":[\"情感支持型\"],\"label\":\"风格类型\"},{\"kind\":\"multi\",\"items\":[\"线下\"],\"label\":\"上课方式\"},{\"label\":\"暑假所在地\",\"value\":\"s\"},{\"label\":\"开学后所在地\",\"value\":\"s\"},{\"label\":\"上课频率\",\"value\":\"s\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"否\"},{\"kind\":\"sort\",\"items\":[\"语文\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"}],\"subtitle\":\"四川大学 · s\"}', '2026-09-17 14:47:47.000', '2026-09-15 07:26:29.000', 'dev-openid-seed-family-01'),
('trial-1789656467505', 'mentor', 'family-dev-openid-seed-family-02', 'terminated', '愿意', '{\"id\":\"family-dev-openid-seed-family-02\",\"badge\":\"家庭\",\"title\":\"黄斯燕\",\"details\":[{\"label\":\"孩子姓名\",\"value\":\"黄斯燕\"},{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"谢阿姨\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"高二\"},{\"label\":\"电话号码\",\"value\":\"19950718717\"},{\"label\":\"微信号\",\"value\":\"innay2025\"},{\"label\":\"常住区域\",\"value\":\"四川省宜宾市\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"语文\",\"英语\"],\"label\":\"需要辅导科目\"},{\"kind\":\"sort\",\"items\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\"],\"label\":\"学习困难\"},{\"kind\":\"sort\",\"items\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"有耐心，善于鼓励，不轻易发脾气\",\"能洞察孩子学习中的困难点，针对性解决\"],\"label\":\"老师特质\"},{\"kind\":\"sort\",\"items\":[\"鼓励陪伴型\"],\"label\":\"教学风格\"},{\"kind\":\"single\",\"label\":\"辅导侧重点\",\"value\":\"讲解基础知识和重要知识点，并进行巩固拔高\"},{\"kind\":\"single\",\"label\":\"关注学习状态\",\"value\":\"非常希望，这有助于提高学习效率。\"},{\"kind\":\"single\",\"label\":\"沟通期望\",\"value\":\"课后能与我简单沟通本次辅导内容和孩子表现。\"},{\"kind\":\"single\",\"label\":\"项目理解\",\"value\":\"基本了解，愿意尝试。\"},{\"kind\":\"single\",\"label\":\"反馈意愿\",\"value\":\"愿意积极配合。\"},{\"kind\":\"multi\",\"items\":[\"线上\",\"线下\"],\"label\":\"上课方式\"},{\"label\":\"上课频率\",\"value\":\"一周1-2次，以后可以根据孩子意愿增加\"},{\"label\":\"过往辅导经历\",\"value\":\"参加过课外辅导，坚持了的效果还可以\"},{\"label\":\"额外备注\",\"value\":\"在现实世界给孩子找一个陪伴和榜样，提升孩子积极心态、学习兴趣和学习能力，拓展视野\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"谢阿姨\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"高二\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"语文\",\"英语\"],\"label\":\"需要辅导科目\"}],\"subtitle\":\"四川省宜宾市\"}', '2026-09-17 14:47:47.000', '2026-09-17 15:35:15.000', 'dev-openid-client-1784996196015-qec9q95u'),
('trial-1789656467505-1cmbl4', 'family', 'mentor-dev-openid-client-1784996196015-qec9q95u', 'terminated', '愿意', '{\"id\":\"mentor-dev-openid-client-1784996196015-qec9q95u\",\"badge\":\"普通成员\",\"title\":\"真机调试账号\",\"details\":[{\"label\":\"姓名\",\"value\":\"真机调试账号\"},{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"否\"},{\"kind\":\"single\",\"label\":\"骨干成员\",\"value\":\"否\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"大二\"},{\"label\":\"学校\",\"value\":\"四川大学\"},{\"label\":\"专业\",\"value\":\"s\"},{\"label\":\"学院\",\"value\":\"s\"},{\"label\":\"微信号\",\"value\":\"s\"},{\"kind\":\"sort\",\"items\":[\"语文\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"},{\"kind\":\"multi\",\"items\":[\"情感支持型\"],\"label\":\"风格类型\"},{\"kind\":\"multi\",\"items\":[\"线下\"],\"label\":\"上课方式\"},{\"label\":\"暑假所在地\",\"value\":\"s\"},{\"label\":\"开学后所在地\",\"value\":\"s\"},{\"label\":\"上课频率\",\"value\":\"s\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"否\"},{\"kind\":\"sort\",\"items\":[\"语文\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"}],\"subtitle\":\"四川大学 · s\"}', '2026-09-17 14:47:47.000', '2026-09-17 15:35:15.000', 'dev-openid-seed-family-02'),
('trial-1789659197745', 'mentor', 'family-dev-openid-seed-family-07', 'pending', '', '{\"id\":\"family-dev-openid-seed-family-07\",\"badge\":\"家庭\",\"title\":\"严一一\",\"details\":[{\"label\":\"孩子姓名\",\"value\":\"严一一\"},{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"一一妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"小学二年级\"},{\"label\":\"电话号码\",\"value\":\"13980086000\"},{\"label\":\"微信号\",\"value\":\"Jiang2L\"},{\"label\":\"常住区域\",\"value\":\"四川省成都市高新区\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"语文\",\"英语\",\"体育\"],\"label\":\"需要辅导科目\"},{\"kind\":\"sort\",\"items\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\",\"其他：他们数学老师是一个比较年轻的新老师，对于孩子的引导上面，方法稍微少了一些。\"],\"label\":\"学习困难\"},{\"kind\":\"sort\",\"items\":[\"学科知识扎实，讲题能力强\",\"讲解清晰有条理，能化繁为简\",\"有耐心，善于鼓励，不轻易发脾气\",\"能帮助孩子建立良好的学习习惯\",\"性格开朗，有亲和力，能调动孩子积极性\",\"能洞察孩子学习中的困难点，针对性解决\"],\"label\":\"老师特质\"},{\"kind\":\"sort\",\"items\":[\"鼓励陪伴型\",\"问题向导型\",\"系统讲解型\",\"启发引导型\"],\"label\":\"教学风格\"},{\"kind\":\"single\",\"label\":\"辅导侧重点\",\"value\":\"紧跟学校进度，预习复习，解答作业疑问\"},{\"kind\":\"single\",\"label\":\"关注学习状态\",\"value\":\"非常希望，这有助于提高学习效率。\"},{\"kind\":\"single\",\"label\":\"沟通期望\",\"value\":\"课后能与我简单沟通本次辅导内容和孩子表现。\"},{\"kind\":\"single\",\"label\":\"项目理解\",\"value\":\"完全理解并认同，相信其专业性。\"},{\"kind\":\"single\",\"label\":\"反馈意愿\",\"value\":\"愿意积极配合。\"},{\"kind\":\"multi\",\"items\":[\"线下\"],\"label\":\"上课方式\"},{\"label\":\"上课频率\",\"value\":\"最好是周一至周五，一周2次\"},{\"label\":\"过往辅导经历\",\"value\":\"我们的课外辅导都是运动和音乐美术类的\"},{\"label\":\"额外备注\",\"value\":\"未填写\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"一一妈妈\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"小学二年级\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"语文\",\"英语\",\"体育\"],\"label\":\"需要辅导科目\"}],\"subtitle\":\"四川省成都市高新区\"}', '2026-09-17 15:33:17.000', '2026-09-17 07:34:11.000', 'dev-openid-client-1785042113258-iqyi6n5p'),
('trial-1789659197745-2zvc4b', 'family', 'mentor-dev-openid-client-1785042113258-iqyi6n5p', 'pending', '', '{\"id\":\"mentor-dev-openid-client-1785042113258-iqyi6n5p\",\"badge\":\"骨干成员\",\"title\":\"真实测试\",\"details\":[{\"label\":\"姓名\",\"value\":\"真实测试\"},{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"single\",\"label\":\"骨干成员\",\"value\":\"是\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"大三\"},{\"label\":\"学校\",\"value\":\"四川大学\"},{\"label\":\"专业\",\"value\":\"人工智能\"},{\"label\":\"学院\",\"value\":\"人工智能\"},{\"label\":\"微信号\",\"value\":\"sdsabab\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\",\"化学\",\"生物\",\"政治\",\"历史\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"},{\"kind\":\"multi\",\"items\":[\"情感支持型\",\"鼓励启发型\",\"灵活应变型\"],\"label\":\"风格类型\"},{\"kind\":\"multi\",\"items\":[\"线上\",\"线下\"],\"label\":\"上课方式\"},{\"label\":\"暑假所在地\",\"value\":\"梧州\"},{\"label\":\"开学后所在地\",\"value\":\"成都\"},{\"label\":\"上课频率\",\"value\":\"商量\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\",\"化学\",\"生物\",\"政治\",\"历史\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"}],\"subtitle\":\"四川大学 · 人工智能\"}', '2026-09-17 15:33:17.000', '2026-09-17 07:34:11.000', 'dev-openid-seed-family-07'),
('trial-1789659206201', 'mentor', 'family-dev-openid-seed-family-06', 'pending', '', '{\"id\":\"family-dev-openid-seed-family-06\",\"badge\":\"家庭\",\"title\":\"徐佳音\",\"details\":[{\"label\":\"孩子姓名\",\"value\":\"徐佳音\"},{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"余女士\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"初一\"},{\"label\":\"电话号码\",\"value\":\"13980700789\"},{\"label\":\"微信号\",\"value\":\"13980700789\"},{\"label\":\"常住区域\",\"value\":\"四川省成都市青羊区\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\"],\"label\":\"需要辅导科目\"},{\"kind\":\"sort\",\"items\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\",\"学习效率低，容易拖延\",\"对科目缺乏兴趣，动力不足\"],\"label\":\"学习困难\"},{\"kind\":\"sort\",\"items\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"认真负责，守时，沟通及时\",\"能洞察孩子学习中的困难点，针对性解决\"],\"label\":\"老师特质\"},{\"kind\":\"sort\",\"items\":[\"系统讲解型\",\"鼓励陪伴型\",\"严格督促型\"],\"label\":\"教学风格\"},{\"kind\":\"single\",\"label\":\"辅导侧重点\",\"value\":\"查缺补漏，专项攻克孩子的薄弱环节\"},{\"kind\":\"single\",\"label\":\"关注学习状态\",\"value\":\"非常希望，这有助于提高学习效率。\"},{\"kind\":\"single\",\"label\":\"沟通期望\",\"value\":\"课后能与我简单沟通本次辅导内容和孩子表现。\"},{\"kind\":\"single\",\"label\":\"项目理解\",\"value\":\"完全理解并认同，相信其专业性。\"},{\"kind\":\"single\",\"label\":\"反馈意愿\",\"value\":\"愿意积极配合。\"},{\"kind\":\"multi\",\"items\":[\"线下\"],\"label\":\"上课方式\"},{\"label\":\"上课频率\",\"value\":\"视情况而定\"},{\"label\":\"过往辅导经历\",\"value\":\"有，效果一般\"},{\"label\":\"额外备注\",\"value\":\"孩子言语发音不清晰，自尊心强\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"孩子性别\",\"value\":\"女\"},{\"label\":\"家长称呼\",\"value\":\"余女士\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"初一\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\"],\"label\":\"需要辅导科目\"}],\"subtitle\":\"四川省成都市青羊区\"}', '2026-09-17 15:33:26.000', '2026-09-16 15:33:26.000', 'dev-openid-client-1785042113258-iqyi6n5p'),
('trial-1789659206201-ypcf1l', 'family', 'mentor-dev-openid-client-1785042113258-iqyi6n5p', 'pending', '', '{\"id\":\"mentor-dev-openid-client-1785042113258-iqyi6n5p\",\"badge\":\"骨干成员\",\"title\":\"真实测试\",\"details\":[{\"label\":\"姓名\",\"value\":\"真实测试\"},{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"single\",\"label\":\"骨干成员\",\"value\":\"是\"},{\"kind\":\"single\",\"label\":\"年级\",\"value\":\"大三\"},{\"label\":\"学校\",\"value\":\"四川大学\"},{\"label\":\"专业\",\"value\":\"人工智能\"},{\"label\":\"学院\",\"value\":\"人工智能\"},{\"label\":\"微信号\",\"value\":\"sdsabab\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\",\"化学\",\"生物\",\"政治\",\"历史\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"},{\"kind\":\"multi\",\"items\":[\"情感支持型\",\"鼓励启发型\",\"灵活应变型\"],\"label\":\"风格类型\"},{\"kind\":\"multi\",\"items\":[\"线上\",\"线下\"],\"label\":\"上课方式\"},{\"label\":\"暑假所在地\",\"value\":\"梧州\"},{\"label\":\"开学后所在地\",\"value\":\"成都\"},{\"label\":\"上课频率\",\"value\":\"商量\"}],\"preview\":[{\"kind\":\"single\",\"label\":\"性别\",\"value\":\"男\"},{\"kind\":\"single\",\"label\":\"项目参与\",\"value\":\"是\"},{\"kind\":\"sort\",\"items\":[\"数学\",\"英语\",\"化学\",\"生物\",\"政治\",\"历史\"],\"label\":\"擅长科目\"},{\"kind\":\"multi\",\"items\":[\"未填写\"],\"label\":\"意向教学年级段\"}],\"subtitle\":\"四川大学 · 人工智能\"}', '2026-09-17 15:33:26.000', '2026-09-16 15:33:26.000', 'dev-openid-seed-family-06');

-- 表 users
CREATE TABLE `users` (
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `profile_json` json NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`openid`,`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `users` (`openid`, `role`, `profile_json`, `created_at`, `updated_at`) VALUES
('dev-openid-0b3syG000aJ0OW1t1S200Uyqib2syG0P', 'mentor', '{\"name\":\"卢生\",\"grade\":\"大二\",\"major\":\"8\",\"gender\":\"男\",\"school\":\"8\",\"wechat\":\"8\",\"college\":\"8\",\"coreMember\":\"是\",\"gradeOther\":\"\",\"mentorProject\":\"是\",\"mentorSubjects\":[\"数学\",\"英语\",\"化学\",\"语文\",\"生物\"],\"mentorStyleTypes\":[\"情感支持型\",\"灵活应变型\",\"鼓励启发型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"8\",\"mentorSchoolLocation\":\"8\",\"mentorSummerLocation\":\"8\",\"mentorTeachingGradeRange\":[]}', '2026-07-02 22:39:17.000', '2026-05-19 06:39:17.000'),
('dev-openid-0c3fBp0006DVNW1Nfo000Lh49k4fBp0N', 'family', '{\"age\":\"\",\"area\":\"其他\",\"name\":\"回合\",\"grade\":\"小学一年级\",\"intro\":\"5\",\"phone\":\"5\",\"gender\":\"男\",\"wechat\":\"5\",\"subjects\":[\"语文\",\"英语\",\"化学\",\"生物\"],\"areaOther\":\"5\",\"extraNote\":\"5\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线下\"],\"parentName\":\"5\",\"difficulties\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\",\"对科目缺乏兴趣，动力不足\",\"其他\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"学科知识扎实，讲题能力强\",\"有耐心，善于鼓励，不轻易发脾气\",\"能帮助孩子建立良好的学习习惯\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"5\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"系统讲解型\",\"问题向导型\",\"启发引导型\"],\"difficultyOther\":\"5\",\"feedbackWillingness\":\"愿意积极配合。\",\"communicationExpectation\":\"除非有特殊情况，否则不需要额外沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-02 22:41:38.000', '2026-05-19 06:41:38.000'),
('dev-openid-0d3W21Ga1Uci7M0WI4Ja1ttwuK2W21G8', 'mentor', '{\"name\":\"香蕉\",\"grade\":\"大三\",\"major\":\"软件工程\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"5555\",\"college\":\"软件学院\",\"coreMember\":\"是\",\"gradeOther\":\"\",\"mentorProject\":\"是\",\"mentorSubjects\":[\"数学\",\"英语\",\"生物\",\"政治\"],\"mentorStyleTypes\":[\"情感支持型\",\"鼓励启发型\",\"灵活应变型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"每周一次\",\"mentorSchoolLocation\":\"成都\",\"mentorSummerLocation\":\"梅州\",\"mentorTeachingGradeRange\":[\"高中\"]}', '2026-07-02 09:00:07.000', '2026-05-18 17:00:12.000'),
('dev-openid-0e3gfhll2gZD8i4Tvtll2m4XrI0gfhlG', 'family', '{\"age\":\"\",\"area\":\"四川省成都市锦江区\",\"name\":\"小米\",\"grade\":\"小学一年级\",\"intro\":\"5\",\"phone\":\"5\",\"gender\":\"男\",\"wechat\":\"5\",\"subjects\":[\"数学\"],\"areaOther\":\"\",\"extraNote\":\"55\",\"mainFocus\":\"紧跟学校进度，预习复习，解答作业疑问\",\"classModes\":[\"线上\"],\"parentName\":\"5\",\"difficulties\":[\"基础知识不牢固\",\"对科目缺乏兴趣，动力不足\"],\"subjectOther\":\"\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"teacherTraits\":[\"学科知识扎实，讲题能力强\",\"有耐心，善于鼓励，不轻易发脾气\",\"性格开朗，有亲和力，能调动孩子积极性\"],\"understanding\":\"完全理解并认同，相信其专业性。\",\"classFrequency\":\"5\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"启发引导型\",\"问题向导型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"需了解具体内容和频率后再决定。\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-02 22:07:43.000', '2026-05-19 06:07:43.000'),
('dev-openid-0e3s4RGa1cDy7M0jdPFa1c8yYM0s4RGY', 'mentor', '{\"name\":\"对对对\",\"grade\":\"大二\",\"major\":\"5\",\"gender\":\"男\",\"school\":\"5\",\"wechat\":\"5\",\"college\":\"5\",\"coreMember\":\"否\",\"gradeOther\":\"\",\"mentorProject\":\"是\",\"mentorSubjects\":[\"语文\",\"数学\",\"英语\",\"化学\"],\"mentorStyleTypes\":[\"情感支持型\",\"鼓励启发型\",\"灵活应变型\",\"结构化引导型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"5\",\"mentorSchoolLocation\":\"5\",\"mentorSummerLocation\":\"5\",\"mentorTeachingGradeRange\":[]}', '2026-07-02 23:24:06.000', '2026-05-19 07:24:06.000'),
('dev-openid-0f3cgmIa1RbbbM0IbjJa18Kril4cgmIH', 'family', '{\"age\":\"\",\"area\":\"四川省成都市金牛区\",\"name\":\"小苹果\",\"grade\":\"小学二年级\",\"intro\":\"55\",\"phone\":\"55\",\"gender\":\"男\",\"wechat\":\"55\",\"subjects\":[\"生物\",\"化学\",\"英语\",\"数学\"],\"areaOther\":\"\",\"extraNote\":\"555\",\"mainFocus\":\"能力拓展，进行拔高训练，提升思维深度\",\"classModes\":[\"线上\",\"线下\"],\"parentName\":\"dd\",\"difficulties\":[\"解题思路不清晰，方法欠缺\",\"基础知识不牢固\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"有耐心，善于鼓励，不轻易发脾气\",\"讲解清晰有条理，能化繁为简\",\"能帮助孩子建立良好的学习习惯\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"1\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"问题向导型\",\"启发引导型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"愿意积极配合\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-02 20:43:49.000', '2026-05-19 04:43:49.000'),
('dev-openid-0f3Y2ZFa1lfH8M02uWFa1u72gA2Y2ZFS', 'mentor', '{\"name\":\"小卢\",\"grade\":\"大四\",\"major\":\"4\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"4\",\"college\":\"4\",\"coreMember\":\"是\",\"gradeOther\":\"\",\"mentorProject\":\"是\",\"mentorSubjects\":[\"英语\",\"数学\",\"化学\",\"生物\",\"政治\"],\"mentorStyleTypes\":[\"情感支持型\",\"鼓励启发型\",\"灵活应变型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"4\",\"mentorSchoolLocation\":\"4\",\"mentorSummerLocation\":\"4\",\"mentorTeachingGradeRange\":[]}', '2026-07-02 22:27:18.000', '2026-05-19 06:27:18.000'),
('dev-openid-client-1784996196015-qec9q95u', 'mentor', '{\"name\":\"真机调试账号\",\"grade\":\"大二\",\"major\":\"s\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"s\",\"college\":\"s\",\"coreMember\":\"否\",\"gradeOther\":\"\",\"mentorProject\":\"否\",\"mentorSubjects\":[\"语文\"],\"mentorStyleTypes\":[\"情感支持型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线下\"],\"mentorClassFrequency\":\"s\",\"mentorSchoolLocation\":\"s\",\"mentorSummerLocation\":\"s\",\"mentorTeachingGradeRange\":[]}', '2026-09-16 15:57:12.000', '2026-08-27 23:57:12.000'),
('dev-openid-client-1784999000363-3j81jb6p', 'family', '{\"age\":\"\",\"area\":\"其他\",\"name\":\"卢智泓\",\"grade\":\"小学二年级\",\"intro\":\"无\",\"phone\":\"15007742584\",\"gender\":\"男\",\"wechat\":\"asdf\",\"subjects\":[\"数学\",\"英语\",\"化学\"],\"areaOther\":\"广西\",\"extraNote\":\"无\",\"mainFocus\":\"能力拓展，进行拔高训练，提升思维深度\",\"classModes\":[\"线上\"],\"parentName\":\"卢\",\"difficulties\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\",\"对科目缺乏兴趣，动力不足\",\"学习效率低，容易拖延\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"学科知识扎实，讲题能力强\",\"讲解清晰有条理，能化繁为简\",\"有耐心，善于鼓励，不轻易发脾气\",\"能帮助孩子建立良好的学习习惯\"],\"understanding\":\"完全理解并认同，相信其专业性。\",\"classFrequency\":\"商量\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"启发引导型\",\"鼓励陪伴型\",\"问题向导型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"需了解具体内容和频率后再决定。\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-04 01:04:16.000', '2026-05-20 09:04:16.000'),
('dev-openid-client-1785039392408-t1wbg02d', 'family', '{\"age\":\"\",\"area\":\"四川省成都市锦江区\",\"name\":\"笑笑\",\"grade\":\"小学六年级\",\"intro\":\"无\",\"phone\":\"15007742584\",\"gender\":\"男\",\"wechat\":\"safadvsfbs\",\"subjects\":[\"数学\",\"英语\",\"生物\",\"政治\",\"历史\"],\"areaOther\":\"\",\"extraNote\":\"无\",\"mainFocus\":\"能力拓展，进行拔高训练，提升思维深度\",\"classModes\":[\"线上\",\"线下\"],\"parentName\":\"小妮\",\"difficulties\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\",\"学习效率低，容易拖延\",\"对科目缺乏兴趣，动力不足\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"学科知识扎实，讲题能力强\",\"讲解清晰有条理，能化繁为简\",\"能帮助孩子建立良好的学习习惯\",\"性格开朗，有亲和力，能调动孩子积极性\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"每周一次\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"启发引导型\",\"鼓励陪伴型\",\"系统讲解型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"需了解具体内容和频率后再决定。\",\"communicationExpectation\":\"除非有特殊情况，否则不需要额外沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-06 04:17:33.000', '2026-05-22 12:17:33.000'),
('dev-openid-client-1785042113258-iqyi6n5p', 'mentor', '{\"name\":\"真实测试\",\"grade\":\"大三\",\"major\":\"人工智能\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"sdsabab\",\"college\":\"人工智能\",\"coreMember\":\"是\",\"gradeOther\":\"\",\"mentorProject\":\"是\",\"mentorSubjects\":[\"数学\",\"英语\",\"化学\",\"生物\",\"政治\",\"历史\"],\"mentorStyleTypes\":[\"情感支持型\",\"鼓励启发型\",\"灵活应变型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"商量\",\"mentorSchoolLocation\":\"成都\",\"mentorSummerLocation\":\"梧州\",\"mentorTeachingGradeRange\":[]}', '2026-07-08 05:02:49.000', '2026-05-24 13:02:49.000'),
('dev-openid-client-1785042644023-ugs60ojj', 'family', '{\"age\":\"\",\"area\":\"四川省成都市高新区\",\"name\":\"小孩\",\"grade\":\"小学四年级\",\"intro\":\"f\",\"phone\":\"f\",\"gender\":\"男\",\"wechat\":\"f\",\"subjects\":[\"化学\",\"数学\",\"英语\",\"政治\"],\"areaOther\":\"\",\"extraNote\":\"f\",\"mainFocus\":\"紧跟学校进度，预习复习，解答作业疑问\",\"classModes\":[\"线上\",\"线下\"],\"parentName\":\"f\",\"difficulties\":[\"解题思路不清晰，方法欠缺\",\"学习效率低，容易拖延\",\"基础知识不牢固\",\"对科目缺乏兴趣，动力不足\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"能帮助孩子建立良好的学习习惯\",\"有耐心，善于鼓励，不轻易发脾气\",\"学科知识扎实，讲题能力强\",\"讲解清晰有条理，能化繁为简\",\"性格开朗，有亲和力，能调动孩子积极性\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"f\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"启发引导型\",\"问题向导型\",\"鼓励陪伴型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"需了解具体内容和频率后再决定。\",\"communicationExpectation\":\"除非有特殊情况，否则不需要额外沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-09 21:11:35.000', '2026-05-26 05:11:35.000'),
('dev-openid-client-1785043393047-s0lh0fuj', 'mentor', '{\"name\":\"卢智浩\",\"grade\":\"大三\",\"major\":\"g\",\"gender\":\"男\",\"school\":\"g\",\"wechat\":\"g\",\"college\":\"g\",\"coreMember\":\"否\",\"gradeOther\":\"\",\"mentorProject\":\"是\",\"mentorSubjects\":[\"语文\",\"数学\",\"化学\"],\"mentorStyleTypes\":[\"鼓励启发型\",\"情感支持型\",\"灵活应变型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线下\",\"线上\"],\"mentorClassFrequency\":\"g\",\"mentorSchoolLocation\":\"g\",\"mentorSummerLocation\":\"g\",\"mentorTeachingGradeRange\":[]}', '2026-07-11 05:23:43.000', '2026-05-27 13:23:43.000'),
('dev-openid-client-1785043845394-5vdletqp', 'family', '{\"age\":\"\",\"area\":\"四川省成都市高新区\",\"name\":\"777777777\",\"grade\":\"小学一年级\",\"intro\":\"7\",\"phone\":\"77\",\"gender\":\"男\",\"wechat\":\"7\",\"subjects\":[\"语文\",\"英语\",\"化学\",\"生物\"],\"areaOther\":\"\",\"extraNote\":\"7\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线下\",\"线上\"],\"parentName\":\"77\",\"difficulties\":[\"基础知识不牢固\",\"对科目缺乏兴趣，动力不足\",\"解题思路不清晰，方法欠缺\",\"学习效率低，容易拖延\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"学科知识扎实，讲题能力强\",\"讲解清晰有条理，能化繁为简\",\"有耐心，善于鼓励，不轻易发脾气\",\"能帮助孩子建立良好的学习习惯\",\"性格开朗，有亲和力，能调动孩子积极性\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"7\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"启发引导型\",\"问题向导型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"需了解具体内容和频率后再决定。\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-12 21:31:18.000', '2026-05-29 05:31:18.000'),
('dev-openid-client-1785044661567-j5d1adqh', 'family', '{\"age\":\"\",\"area\":\"四川省成都市锦江区\",\"name\":\"哈哈哈\",\"grade\":\"小学二年级\",\"intro\":\"5\",\"phone\":\"1500742584\",\"gender\":\"男\",\"wechat\":\"afaf\",\"subjects\":[\"数学\",\"语文\",\"英语\",\"化学\",\"体育\"],\"areaOther\":\"\",\"extraNote\":\"5\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线上\",\"线下\"],\"parentName\":\"小米\",\"difficulties\":[\"基础知识不牢固\",\"学习效率低，容易拖延\",\"对科目缺乏兴趣，动力不足\",\"解题思路不清晰，方法欠缺\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"学科知识扎实，讲题能力强\",\"有耐心，善于鼓励，不轻易发脾气\",\"讲解清晰有条理，能化繁为简\",\"能帮助孩子建立良好的学习习惯\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"5\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"鼓励陪伴型\",\"启发引导型\",\"问题向导型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-13 21:45:07.000', '2026-05-30 05:45:07.000'),
('dev-openid-client-1785044767504-gcg4ir94', 'family', '{\"age\":\"\",\"area\":\"其他\",\"name\":\"111\",\"grade\":\"小学四年级\",\"intro\":\"1\",\"phone\":\"1\",\"gender\":\"男\",\"wechat\":\"1\",\"subjects\":[\"语文\",\"绘画\"],\"areaOther\":\"1\",\"extraNote\":\"1\",\"mainFocus\":\"紧跟学校进度，预习复习，解答作业疑问\",\"classModes\":[\"线下\",\"线上\"],\"parentName\":\"1\",\"difficulties\":[\"解题思路不清晰，方法欠缺\",\"考试时容易紧张，发挥失常\"],\"subjectOther\":\"\",\"learningState\":\"不太需要，主要辅导好知识点即可\",\"teacherTraits\":[\"能帮助孩子建立良好的学习习惯\",\"认真负责，守时，沟通及时\",\"有耐心，善于鼓励，不轻易发脾气\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"1\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"启发引导型\",\"问题向导型\",\"鼓励陪伴型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"communicationExpectation\":\"除非有特殊情况，否则不需要额外沟通。\",\"communicationExpectationOther\":\"\"}', '2026-07-15 05:46:39.000', '2026-05-31 13:46:39.000'),
('dev-openid-client-1789449585184-gcey804g', 'family', '{\"age\":\"\",\"area\":\"四川省成都市青羊区\",\"name\":\"ttt\",\"grade\":\"小学一年级\",\"intro\":\"t\",\"phone\":\"t\",\"gender\":\"男\",\"wechat\":\"t\",\"subjects\":[\"语文\",\"绘画\"],\"areaOther\":\"\",\"extraNote\":\"t\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线上\"],\"parentName\":\"t\",\"difficulties\":[\"对科目缺乏兴趣，动力不足\",\"解题思路不清晰，方法欠缺\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"teacherTraits\":[\"讲解清晰有条理，能化繁为简\"],\"understanding\":\"基本了解，愿意尝试。\",\"classFrequency\":\"t\",\"mainFocusOther\":\"\",\"teachingStyles\":[\"问题向导型\"],\"difficultyOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"communicationExpectation\":\"课后能与我简单沟通本次辅导内容和孩子表现。\",\"communicationExpectationOther\":\"\"}', '2026-09-15 05:20:17.000', '2026-08-07 05:20:17.000'),
('dev-openid-client-1789450300455-7ve2svkj', 'mentor', '{\"name\":\"ttt\",\"grade\":\"大五\",\"major\":\"e\",\"gender\":\"男\",\"school\":\"e\",\"wechat\":\"t\",\"college\":\"e\",\"coreMember\":\"是\",\"gradeOther\":\"\",\"mentorProject\":\"否\",\"mentorSubjects\":[\"英语\"],\"mentorStyleTypes\":[\"情感支持型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\"],\"mentorClassFrequency\":\"e\",\"mentorSchoolLocation\":\"e\",\"mentorSummerLocation\":\"e\",\"mentorTeachingGradeRange\":[]}', '2026-09-15 05:33:05.000', '2026-08-08 21:33:05.000'),
('dev-openid-client-1789482263819-ey12ipnt', 'mentor', '{\"name\":\"方法\",\"grade\":\"大二\",\"major\":\"k\",\"gender\":\"女\",\"school\":\"k\",\"wechat\":\"h\",\"college\":\"h\",\"coreMember\":\"否\",\"gradeOther\":\"\",\"mentorProject\":\"否\",\"mentorSubjects\":[\"化学\"],\"mentorStyleTypes\":[\"鼓励启发型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\"],\"mentorClassFrequency\":\"h\",\"mentorSchoolLocation\":\"h\",\"mentorSummerLocation\":\"h\",\"mentorTeachingGradeRange\":[]}', '2026-09-15 14:24:47.000', '2026-08-10 14:24:47.000'),
('dev-openid-client-1789560203315-q4zsvi37', 'mentor', '{\"name\":\"2026.9.16\",\"grade\":\"大二\",\"major\":\"软件工程\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"33\",\"college\":\"软件学院\",\"coreMember\":\"是\",\"gradeOther\":\"\",\"mentorProject\":\"是\",\"mentorSubjects\":[\"数学\",\"语文\"],\"mentorStyleTypes\":[\"鼓励启发型\"],\"mentorSubjectOther\":\"\",\"mentorTeachingModes\":[\"线上\"],\"mentorClassFrequency\":\"88\",\"mentorSchoolLocation\":\"44\",\"mentorSummerLocation\":\"3\",\"mentorTeachingGradeRange\":[]}', '2026-09-16 12:04:39.000', '2026-08-16 04:04:39.000'),
('dev-openid-seed-family-01', 'family', '{\"age\":\"\",\"area\":\"四川省成都市高新区\",\"city\":\"\",\"name\":\"严耀国\",\"grade\":\"小学四年级\",\"intro\":\"他曾经学过硬笔书法，篮球、游泳、羽毛球，英语，国学古诗词。\",\"major\":\"\",\"phone\":\"13980086000\",\"gender\":\"男\",\"school\":\"\",\"wechat\":\"Jiang2L\",\"college\":\"\",\"subjects\":[\"体育\",\"语文\",\"数学\",\"英语\",\"地理\",\"化学\"],\"areaOther\":\"\",\"extraNote\":\"从2024年张骏老师团队在高新区分享青少年成长问题，就有关注，但那个时候觉得孩子可能年龄还比较小，自认为还没有达到匹配程度，所以也一直在持续关注。\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"蹦蹦妈妈\",\"difficulties\":[\"学习效率低，容易拖延\",\"对科目缺乏兴趣，动力不足\",\"解题思路不清晰，方法欠缺\",\"基础知识不牢固\",\"其他\"],\"subjectOther\":\"孩子对历史和地理比较感兴趣，他的身体比较瘦，专注力比较差，我们希望找到一个热爱运动，活泼开朗有耐心的老师。\",\"learningState\":\"可以接受，顺其自然。\",\"mentorProject\":\"\",\"teacherTraits\":[\"能帮助孩子建立良好的学习习惯\",\"有耐心，善于鼓励，不轻易发脾气\",\"性格开朗，有亲和力，能调动孩子积极性\",\"讲解清晰有条理，能化繁为简\",\"能洞察孩子学习中的困难点，针对性解决\"],\"understanding\":\"完全理解并认同，相信其专业性。\",\"classFrequency\":\"工作日每天\",\"mainFocusOther\":\"希望每一次课都有涉及一些有趣的知识环节，可以是大学自己所学相关专业的兴趣分享，可以让小朋友们建立更深的友谊和信任。\",\"mentorSubjects\":[],\"teachingStyles\":[\"启发引导型\",\"鼓励陪伴型\",\"问题向导型\"],\"difficultyOther\":\"华西附二院诊断他有轻微的抽动症\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"课后能与我简单沟通本次辅导内容和孩子表现。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"希望老师能够通过自身的学习经验，正确引导，让他能够提高一些学习效率。\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-02', 'family', '{\"age\":\"\",\"area\":\"其他\",\"city\":\"\",\"name\":\"黄斯燕\",\"grade\":\"高二\",\"intro\":\"参加过课外辅导，坚持了的效果还可以\",\"major\":\"\",\"phone\":\"19950718717\",\"gender\":\"女\",\"school\":\"\",\"wechat\":\"innay2025\",\"college\":\"\",\"subjects\":[\"数学\",\"语文\",\"英语\"],\"areaOther\":\"四川省宜宾市\",\"extraNote\":\"在现实世界给孩子找一个陪伴和榜样，提升孩子积极心态、学习兴趣和学习能力，拓展视野\",\"mainFocus\":\"其他\",\"classModes\":[\"线上\",\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"谢阿姨\",\"difficulties\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\"],\"subjectOther\":\"物理，化学\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"有耐心，善于鼓励，不轻易发脾气\",\"能洞察孩子学习中的困难点，针对性解决\"],\"understanding\":\"基本了解，愿意尝试。\",\"classFrequency\":\"一周1-2次，以后可以根据孩子意愿增加\",\"mainFocusOther\":\"讲解基础知识和重要知识点，并进行巩固拔高\",\"mentorSubjects\":[],\"teachingStyles\":[\"鼓励陪伴型\"],\"difficultyOther\":\"欠了很多课没学，学习人际压力，有抑郁焦虑情绪，回避上学在家过度上网\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"课后能与我简单沟通本次辅导内容和孩子表现。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-03', 'family', '{\"age\":\"\",\"area\":\"其他\",\"city\":\"\",\"name\":\"七七\",\"grade\":\"初一\",\"intro\":\"有参加过其他补习，但是学过就忘\",\"major\":\"\",\"phone\":\"18982812939\",\"gender\":\"女\",\"school\":\"\",\"wechat\":\"18982812939\",\"college\":\"\",\"subjects\":[\"数学\",\"英语\"],\"areaOther\":\"四川达州大竹\",\"extraNote\":\"项目对老师的工作怎么进行监管？\",\"mainFocus\":\"其他\",\"classModes\":[\"线上\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"七七妈妈\",\"difficulties\":[\"考试时容易紧张，发挥失常\",\"解题思路不清晰，方法欠缺\",\"学习效率低，容易拖延\"],\"subjectOther\":\"\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"有耐心，善于鼓励，不轻易发脾气\",\"能帮助孩子建立良好的学习习惯\",\"性格开朗，有亲和力，能调动孩子积极性\",\"能洞察孩子学习中的困难点，针对性解决\",\"讲解清晰有条理，能化繁为简\"],\"understanding\":\"基本了解，愿意尝试。\",\"classFrequency\":\"老师根据孩子状态来安排\",\"mainFocusOther\":\"怀疑自己的学习能力，已经处于习得性无助状态。需要先建立她对学习的信心和兴趣。\",\"mentorSubjects\":[],\"teachingStyles\":[\"鼓励陪伴型\",\"启发引导型\"],\"difficultyOther\":\"孩子在用药治疗，情绪稳定、记忆力下降、注意力无法集中没有得到改善、焦虑还比较明显，经常抠指甲咬指甲；怀疑自己的学习能力，说前面学过的内容都忘光了。\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"老师能给予孩子情感上的陪伴和支持\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-04', 'family', '{\"age\":\"\",\"area\":\"四川省成都市金牛区\",\"city\":\"\",\"name\":\"孙逸宸\",\"grade\":\"初二\",\"intro\":\"多次参加\",\"major\":\"\",\"phone\":\"\",\"gender\":\"男\",\"school\":\"\",\"wechat\":\"13438889034\",\"college\":\"\",\"subjects\":[\"语文\",\"数学\"],\"areaOther\":\"\",\"extraNote\":\"孩子上学很老火，存在一定的躯体化反应\",\"mainFocus\":\"能力拓展，进行拔高训练，提升思维深度\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"冯女士\",\"difficulties\":[\"其他\"],\"subjectOther\":\"心理抗拒语文\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"讲解清晰有条理，能化繁为简\",\"能洞察孩子学习中的困难点，针对性解决\",\"认真负责，守时，沟通及时\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"根据孩子具体情况，老师决定\",\"mainFocusOther\":\"孩子学习能力较强，就是无主动学习的意识。\",\"mentorSubjects\":[],\"teachingStyles\":[\"问题向导型\",\"鼓励陪伴型\"],\"difficultyOther\":\"有退缩行为\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"课后能与我简单沟通本次辅导内容和孩子表现。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"认知上的引导\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-05', 'family', '{\"age\":\"\",\"area\":\"四川省成都市锦江区\",\"city\":\"\",\"name\":\"阳张新一\",\"grade\":\"小学三年级\",\"intro\":\"数学有参加课外辅导 效果不太好\",\"major\":\"\",\"phone\":\"13541262373\",\"gender\":\"男\",\"school\":\"\",\"wechat\":\"13541262373\",\"college\":\"\",\"subjects\":[\"语文\",\"数学\"],\"areaOther\":\"\",\"extraNote\":\"我也曾是华西的学生 相信每一次项目的意义 很愿意积极参与该项目 最终达到双赢\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"张萍\",\"difficulties\":[\"对科目缺乏兴趣，动力不足\",\"学习效率低，容易拖延\",\"解题思路不清晰，方法欠缺\"],\"subjectOther\":\"\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"能洞察孩子学习中的困难点，针对性解决\",\"能帮助孩子建立良好的学习习惯\"],\"understanding\":\"完全理解并认同，相信其专业性。\",\"classFrequency\":\"每周一次\",\"mainFocusOther\":\"建立清晰的思维逻辑\",\"mentorSubjects\":[],\"teachingStyles\":[\"启发引导型\",\"问题向导型\"],\"difficultyOther\":\"畏难情绪比较严重\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"及时给家长反馈观察到的问题\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-06', 'family', '{\"age\":\"\",\"area\":\"四川省成都市青羊区\",\"city\":\"\",\"name\":\"徐佳音\",\"grade\":\"初一\",\"intro\":\"有，效果一般\",\"major\":\"\",\"phone\":\"13980700789\",\"gender\":\"女\",\"school\":\"\",\"wechat\":\"13980700789\",\"college\":\"\",\"subjects\":[\"数学\",\"英语\"],\"areaOther\":\"\",\"extraNote\":\"孩子言语发音不清晰，自尊心强\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"余女士\",\"difficulties\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\",\"学习效率低，容易拖延\",\"对科目缺乏兴趣，动力不足\"],\"subjectOther\":\"语文\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"认真负责，守时，沟通及时\",\"能洞察孩子学习中的困难点，针对性解决\"],\"understanding\":\"完全理解并认同，相信其专业性。\",\"classFrequency\":\"视情况而定\",\"mainFocusOther\":\"激发学习内驱力，改善畏难情绪\",\"mentorSubjects\":[],\"teachingStyles\":[\"系统讲解型\",\"鼓励陪伴型\",\"严格督促型\"],\"difficultyOther\":\"畏难情绪严重\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"课后能与我简单沟通本次辅导内容和孩子表现。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-07', 'family', '{\"age\":\"\",\"area\":\"四川省成都市高新区\",\"city\":\"\",\"name\":\"严一一\",\"grade\":\"小学二年级\",\"intro\":\"我们的课外辅导都是运动和音乐美术类的\",\"major\":\"\",\"phone\":\"13980086000\",\"gender\":\"女\",\"school\":\"\",\"wechat\":\"Jiang2L\",\"college\":\"\",\"subjects\":[\"数学\",\"语文\",\"英语\",\"体育\"],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"紧跟学校进度，预习复习，解答作业疑问\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"一一妈妈\",\"difficulties\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\",\"其他\"],\"subjectOther\":\"小朋友属于比较自律的孩子，希望找到一个陪伴的大哥哥姐姐，有经验能够理解这么大的孩子的思维\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"学科知识扎实，讲题能力强\",\"讲解清晰有条理，能化繁为简\",\"有耐心，善于鼓励，不轻易发脾气\",\"能帮助孩子建立良好的学习习惯\",\"性格开朗，有亲和力，能调动孩子积极性\",\"能洞察孩子学习中的困难点，针对性解决\"],\"understanding\":\"完全理解并认同，相信其专业性。\",\"classFrequency\":\"最好是周一至周五，一周2次\",\"mainFocusOther\":\"解决完作业的疑点难点后，能够查漏补缺。\",\"mentorSubjects\":[],\"teachingStyles\":[\"鼓励陪伴型\",\"问题向导型\",\"系统讲解型\",\"启发引导型\"],\"difficultyOther\":\"他们数学老师是一个比较年轻的新老师，对于孩子的引导上面，方法稍微少了一些。\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"课后能与我简单沟通本次辅导内容和孩子表现。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"希望哥哥或姐姐活泼，爱聊天。因为我们家孩子在学校属于比较乖的，我不希望她只是比较沉闷的做题，希望他也可以了解现在川大优秀的哥哥姐姐的生活。\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-08', 'family', '{\"age\":\"\",\"area\":\"四川省成都市其他区县\",\"city\":\"\",\"name\":\"周正扬\",\"grade\":\"初三\",\"intro\":\"小学三年级后没有补课，开始厌学\",\"major\":\"\",\"phone\":\"13981737968\",\"gender\":\"男\",\"school\":\"\",\"wechat\":\"13981737968\",\"college\":\"\",\"subjects\":[\"数学\",\"英语\",\"物理\",\"化学\"],\"areaOther\":\"新都区大丰博雅新城D区\",\"extraNote\":\"\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"潘俊\",\"difficulties\":[\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\"],\"subjectOther\":\"\",\"learningState\":\"可以接受，顺其自然。\",\"mentorProject\":\"\",\"teacherTraits\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"能洞察孩子学习中的困难点，针对性解决\",\"能帮助孩子建立良好的学习习惯\",\"讲解清晰有条理，能化繁为简\",\"学科知识扎实，讲题能力强\"],\"understanding\":\"完全理解并认同，相信其专业性。\",\"classFrequency\":\"每周一次\",\"mainFocusOther\":\"跟孩子多交流，陪孩子找到学习的动力和方法\",\"mentorSubjects\":[],\"teachingStyles\":[\"启发引导型\",\"鼓励陪伴型\",\"系统讲解型\"],\"difficultyOther\":\"心理能力比较弱，自我否定\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"定期（如每周/每月）有一次详细沟通。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"关注孩子情绪和状态\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-09', 'family', '{\"age\":\"\",\"area\":\"四川省成都市高新区\",\"city\":\"\",\"name\":\"陈柔山\",\"grade\":\"高二\",\"intro\":\"是\",\"major\":\"\",\"phone\":\"13608060777\",\"gender\":\"男\",\"school\":\"\",\"wechat\":\"13608060777\",\"college\":\"\",\"subjects\":[\"其他\"],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"其他\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"山妈\",\"difficulties\":[\"对科目缺乏兴趣，动力不足\",\"其他\"],\"subjectOther\":\"AI、游戏编程和运动\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"性格开朗，有亲和力，能调动孩子积极性\",\"能洞察孩子学习中的困难点，针对性解决\",\"有耐心，善于鼓励，不轻易发脾气\"],\"understanding\":\"希望了解更多细节。\",\"classFrequency\":\"每周一次\",\"mainFocusOther\":\"大哥哥帮助他正确认识理解生活学习上的困难、积极阳光的态度面对生活\",\"mentorSubjects\":[],\"teachingStyles\":[\"鼓励陪伴型\",\"启发引导型\"],\"difficultyOther\":\"起床困难\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"其他\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"多和孩子玩儿，在游戏和运动中让孩子体验乐趣和快乐\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-family-10', 'family', '{\"age\":\"\",\"area\":\"四川省成都市锦江区\",\"city\":\"\",\"name\":\"李璐\",\"grade\":\"高二\",\"intro\":\"参加过，效果不好\",\"major\":\"\",\"phone\":\"13541226138\",\"gender\":\"女\",\"school\":\"\",\"wechat\":\"13541226138\",\"college\":\"\",\"subjects\":[\"数学\",\"物理\",\"化学\"],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"查缺补漏，专项攻克孩子的薄弱环节\",\"classModes\":[\"线下\"],\"coreMember\":\"\",\"gradeOther\":\"\",\"parentName\":\"曲\",\"difficulties\":[\"对科目缺乏兴趣，动力不足\",\"学习效率低，容易拖延\",\"基础知识不牢固\",\"解题思路不清晰，方法欠缺\"],\"subjectOther\":\"英语\",\"learningState\":\"非常希望，这有助于提高学习效率。\",\"mentorProject\":\"\",\"teacherTraits\":[\"能洞察孩子学习中的困难点，针对性解决\",\"能帮助孩子建立良好的学习习惯\",\"性格开朗，有亲和力，能调动孩子积极性\"],\"understanding\":\"基本了解，愿意尝试。\",\"classFrequency\":\"每周3-5次\",\"mainFocusOther\":\"提升学生的内驱力\",\"mentorSubjects\":[],\"teachingStyles\":[\"启发引导型\"],\"difficultyOther\":\"不想学 碰到问题不愿思考\",\"mentorStyleTypes\":[],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"愿意积极配合。\",\"mentorTeachingModes\":[],\"mentorClassFrequency\":\"\",\"mentorSchoolLocation\":\"\",\"mentorSummerLocation\":\"\",\"communicationExpectation\":\"课后能与我简单沟通本次辅导内容和孩子表现。\",\"mentorTeachingGradeRange\":\"\",\"communicationExpectationOther\":\"激发学生学习兴趣\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-01', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"易灵苓\",\"grade\":\"2024级\",\"intro\":\"\",\"major\":\"预防医学\",\"phone\":\"13479282296\",\"gender\":\"女\",\"school\":\"四川大学\",\"wechat\":\"IcebergLettuces\",\"college\":\"华西公共卫生学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"语文\",\"英语\",\"生物\",\"数学\",\"物理\",\"化学\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"结构化引导型\",\"耐心倾听型\",\"情感支持型\"],\"mentorSubjectOther\":\"更擅长偏文科的科目，但高中学的全理，也可以提供物化辅导。高考英语146\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线下\",\"线上\"],\"mentorClassFrequency\":\"线下一周1-2次，线上可以更多一些\",\"mentorSchoolLocation\":\"成都\",\"mentorSummerLocation\":\"江西\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"小学\",\"高中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-02', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"杨红娟\",\"grade\":\"2024级\",\"intro\":\"\",\"major\":\"汉语言文学\",\"phone\":\"13708209324\",\"gender\":\"女\",\"school\":\"四川大学\",\"wechat\":\"yhj18129221651\",\"college\":\"文学与新闻学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"语文\",\"英语\",\"历史\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"鼓励启发型\",\"情感支持型\",\"耐心倾听型\"],\"mentorSubjectOther\":\"小学阶段数学\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"一周一到两回(可以商议)\",\"mentorSchoolLocation\":\"成都\",\"mentorSummerLocation\":\"乌鲁木齐\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"小学\",\"初中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-03', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"严艺萌\",\"grade\":\"2025级\",\"intro\":\"\",\"major\":\"文物与博物馆学\",\"phone\":\"15388117397\",\"gender\":\"女\",\"school\":\"四川大学\",\"wechat\":\"wxyym0707070q\",\"college\":\"历史文化学院（考古文博学院）\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"英语\",\"语文\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"情感支持型\",\"鼓励启发型\",\"耐心倾听型\"],\"mentorSubjectOther\":\"历史、地理、政治、音乐（长笛）\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线下\",\"线上\"],\"mentorClassFrequency\":\"一周一次\",\"mentorSchoolLocation\":\"四川省成都市双流区\",\"mentorSummerLocation\":\"四川省成都市武侯区\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"小学\",\"初中\",\"高中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-04', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"李冀宽\",\"grade\":\"2025\",\"intro\":\"\",\"major\":\"基础医学\",\"phone\":\"18225142676\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"wxid_i9qoajhvc2ju12 电话：18225142676\",\"college\":\"华西基础医学与法医学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"英语\",\"生物\",\"数学\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"结构化引导型\",\"情感支持型\",\"鼓励启发型\",\"灵活应变型\",\"耐心倾听型\"],\"mentorSubjectOther\":\"物理、化学\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"一周一次\",\"mentorSchoolLocation\":\"成都市双流区\",\"mentorSummerLocation\":\"重庆市南川区\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"小学\",\"初中\",\"高中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-05', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"康元松\",\"grade\":\"大一\",\"intro\":\"\",\"major\":\"化学类\",\"phone\":\"19720332646\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"wx19720332646\",\"college\":\"化学学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"化学\",\"物理\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"鼓励启发型\"],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线上\"],\"mentorClassFrequency\":\"一周一到两次，周六末\",\"mentorSchoolLocation\":\"成都\",\"mentorSummerLocation\":\"成都\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"高中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-06', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"罗桂英\",\"grade\":\"2024级\",\"intro\":\"\",\"major\":\"汉语言文学\",\"phone\":\"18982849139\",\"gender\":\"女\",\"school\":\"四川大学\",\"wechat\":\"18982849139\",\"college\":\"文学与新闻学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"语文\",\"数学\",\"英语\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"情感支持型\",\"鼓励启发型\",\"结构化引导型\",\"耐心倾听型\"],\"mentorSubjectOther\":\"历史\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"暑假期间可以两天一节（可以调整）\",\"mentorSchoolLocation\":\"成都\",\"mentorSummerLocation\":\"成都\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-07', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"张梓彤\",\"grade\":\"2025级\",\"intro\":\"\",\"major\":\"马克思主义理论\",\"phone\":\"18628007560\",\"gender\":\"女\",\"school\":\"四川大学\",\"wechat\":\"18628007560\",\"college\":\"马克思主义学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"语文\",\"数学\",\"历史\",\"体育\",\"政治\",\"地理\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"情感支持型\",\"耐心倾听型\",\"鼓励启发型\",\"灵活应变型\"],\"mentorSubjectOther\":\"陪伴\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线上\",\"线下\"],\"mentorClassFrequency\":\"每周2—3次\",\"mentorSchoolLocation\":\"成都市双流区四川大学江安校区\",\"mentorSummerLocation\":\"云南省\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-08', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"蒋慧博（现在还可接课）\",\"grade\":\"2024级\",\"intro\":\"\",\"major\":\"英语\",\"phone\":\"\",\"gender\":\"女\",\"school\":\"四川大学\",\"wechat\":\"jhy15506108308\",\"college\":\"外国语学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"英语\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"结构化引导型\",\"情感支持型\",\"鼓励启发型\",\"灵活应变型\",\"耐心倾听型\"],\"mentorSubjectOther\":\"语文\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线下\",\"线上\"],\"mentorClassFrequency\":\"暑期可以每天上课，开学后一周1-2次\",\"mentorSchoolLocation\":\"成都，川大江安校区\",\"mentorSummerLocation\":\"8.15前在江苏，8.16后都在成都\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"小学\",\"初中\",\"高中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-09', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"李悦涵\",\"grade\":\"2025级\",\"intro\":\"\",\"major\":\"数学与智能科技\",\"phone\":\"13778218937\",\"gender\":\"女\",\"school\":\"四川大学\",\"wechat\":\"13778218937\",\"college\":\"数学学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"语文\",\"数学\",\"英语\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"灵活应变型\",\"耐心倾听型\",\"结构化引导型\",\"鼓励启发型\"],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线下\"],\"mentorClassFrequency\":\"一周一次\",\"mentorSchoolLocation\":\"成都\",\"mentorSummerLocation\":\"成都\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"高中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000'),
('dev-openid-seed-mentor-10', 'mentor', '{\"age\":\"\",\"area\":\"\",\"city\":\"\",\"name\":\"王士豪\",\"grade\":\"2024级\",\"intro\":\"\",\"major\":\"临床医学五年制\",\"phone\":\"17682968376\",\"gender\":\"男\",\"school\":\"四川大学\",\"wechat\":\"17682968376\",\"college\":\"华西临床医学院\",\"subjects\":[],\"areaOther\":\"\",\"extraNote\":\"\",\"mainFocus\":\"\",\"classModes\":[],\"coreMember\":\"否\",\"gradeOther\":\"\",\"parentName\":\"\",\"difficulties\":[],\"subjectOther\":\"\",\"learningState\":\"\",\"mentorProject\":\"是\",\"teacherTraits\":[],\"understanding\":\"\",\"classFrequency\":\"\",\"mainFocusOther\":\"\",\"mentorSubjects\":[\"物理\",\"数学\",\"化学\",\"生物\"],\"teachingStyles\":[],\"difficultyOther\":\"\",\"mentorStyleTypes\":[\"结构化引导型\",\"耐心倾听型\",\"情感支持型\",\"鼓励启发型\"],\"mentorSubjectOther\":\"\",\"feedbackWillingness\":\"\",\"mentorTeachingModes\":[\"线下\"],\"mentorClassFrequency\":\"每周一次\",\"mentorSchoolLocation\":\"四川省成都市川大华西校区\",\"mentorSummerLocation\":\"四川省成都市川大华西校区\",\"communicationExpectation\":\"\",\"mentorTeachingGradeRange\":[\"初中\",\"高中\"],\"communicationExpectationOther\":\"\"}', '2026-09-17 13:07:34.000', '2026-09-05 13:07:34.000');

-- 视图 family_profiles_view
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `family_profiles_view` AS select `users`.`openid` AS `openid`,`users`.`role` AS `role`,json_unquote(json_extract(`users`.`profile_json`,'$.name')) AS `child_name`,json_unquote(json_extract(`users`.`profile_json`,'$.parentName')) AS `parent_name`,json_unquote(json_extract(`users`.`profile_json`,'$.phone')) AS `phone`,json_unquote(json_extract(`users`.`profile_json`,'$.wechat')) AS `wechat`,(case when (json_unquote(json_extract(`users`.`profile_json`,'$.area')) = '其他') then json_unquote(json_extract(`users`.`profile_json`,'$.areaOther')) else json_unquote(json_extract(`users`.`profile_json`,'$.area')) end) AS `area_text`,json_unquote(json_extract(`users`.`profile_json`,'$.gender')) AS `gender`,(case when (json_unquote(json_extract(`users`.`profile_json`,'$.grade')) = '其他') then json_unquote(json_extract(`users`.`profile_json`,'$.gradeOther')) else json_unquote(json_extract(`users`.`profile_json`,'$.grade')) end) AS `grade_text`,json_extract(`users`.`profile_json`,'$.subjects') AS `subjects_json`,json_extract(`users`.`profile_json`,'$.difficulties') AS `difficulties_json`,json_extract(`users`.`profile_json`,'$.teacherTraits') AS `teacher_traits_json`,json_extract(`users`.`profile_json`,'$.teachingStyles') AS `teaching_styles_json`,(case when (json_unquote(json_extract(`users`.`profile_json`,'$.mainFocus')) = '其他') then json_unquote(json_extract(`users`.`profile_json`,'$.mainFocusOther')) else json_unquote(json_extract(`users`.`profile_json`,'$.mainFocus')) end) AS `main_focus_text`,json_unquote(json_extract(`users`.`profile_json`,'$.learningState')) AS `learning_state`,(case when (json_unquote(json_extract(`users`.`profile_json`,'$.communicationExpectation')) = '其他') then json_unquote(json_extract(`users`.`profile_json`,'$.communicationExpectationOther')) else json_unquote(json_extract(`users`.`profile_json`,'$.communicationExpectation')) end) AS `communication_expectation_text`,json_unquote(json_extract(`users`.`profile_json`,'$.understanding')) AS `understanding`,json_unquote(json_extract(`users`.`profile_json`,'$.feedbackWillingness')) AS `feedback_willingness`,json_extract(`users`.`profile_json`,'$.classModes') AS `class_modes_json`,json_unquote(json_extract(`users`.`profile_json`,'$.classFrequency')) AS `class_frequency`,json_unquote(json_extract(`users`.`profile_json`,'$.intro')) AS `intro`,json_unquote(json_extract(`users`.`profile_json`,'$.extraNote')) AS `extra_note`,`users`.`created_at` AS `created_at`,`users`.`updated_at` AS `updated_at` from `users` where (`users`.`role` = 'family');

-- 视图 family_trial_feedback_view
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `family_trial_feedback_view` AS select `family_trial_feedback`.`id` AS `id`,`family_trial_feedback`.`openid` AS `openid`,`family_trial_feedback`.`trial_record_id` AS `trial_record_id`,`family_trial_feedback`.`card_id` AS `card_id`,`family_trial_feedback`.`target_title` AS `target_title`,`family_trial_feedback`.`target_subtitle` AS `target_subtitle`,`family_trial_feedback`.`trial_date` AS `trial_date`,`family_trial_feedback`.`trial_duration` AS `trial_duration`,`family_trial_feedback`.`satisfaction_points_json` AS `satisfaction_points_json`,`family_trial_feedback`.`satisfaction_point_other` AS `satisfaction_point_other`,`family_trial_feedback`.`objective_unsatisfied_json` AS `objective_unsatisfied_json`,`family_trial_feedback`.`objective_unsatisfied_other` AS `objective_unsatisfied_other`,`family_trial_feedback`.`subjective_unsatisfied_json` AS `subjective_unsatisfied_json`,`family_trial_feedback`.`subjective_unsatisfied_other` AS `subjective_unsatisfied_other`,`family_trial_feedback`.`continue_choice` AS `continue_choice`,`family_trial_feedback`.`continue_choice_other` AS `continue_choice_other`,`family_trial_feedback`.`status_after_feedback` AS `status_after_feedback`,`family_trial_feedback`.`created_at` AS `created_at`,`family_trial_feedback`.`updated_at` AS `updated_at` from `family_trial_feedback` order by `family_trial_feedback`.`updated_at` desc,`family_trial_feedback`.`created_at` desc;

-- 视图 mentor_profiles_view
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `mentor_profiles_view` AS select `users`.`openid` AS `openid`,`users`.`role` AS `role`,json_unquote(json_extract(`users`.`profile_json`,'$.name')) AS `name`,json_unquote(json_extract(`users`.`profile_json`,'$.gender')) AS `gender`,json_unquote(json_extract(`users`.`profile_json`,'$.mentorProject')) AS `mentor_project`,json_unquote(json_extract(`users`.`profile_json`,'$.coreMember')) AS `core_member`,(case when (json_unquote(json_extract(`users`.`profile_json`,'$.grade')) = '其他') then json_unquote(json_extract(`users`.`profile_json`,'$.gradeOther')) else json_unquote(json_extract(`users`.`profile_json`,'$.grade')) end) AS `grade_text`,json_unquote(json_extract(`users`.`profile_json`,'$.school')) AS `school`,json_unquote(json_extract(`users`.`profile_json`,'$.major')) AS `major`,json_unquote(json_extract(`users`.`profile_json`,'$.college')) AS `college`,json_unquote(json_extract(`users`.`profile_json`,'$.wechat')) AS `wechat`,json_extract(`users`.`profile_json`,'$.mentorSubjects') AS `mentor_subjects_json`,json_extract(`users`.`profile_json`,'$.mentorTeachingGradeRange') AS `mentor_teaching_grade_range_json`,json_extract(`users`.`profile_json`,'$.mentorStyleTypes') AS `mentor_style_types_json`,json_extract(`users`.`profile_json`,'$.mentorTeachingModes') AS `mentor_teaching_modes_json`,json_unquote(json_extract(`users`.`profile_json`,'$.mentorSummerLocation')) AS `mentor_summer_location`,json_unquote(json_extract(`users`.`profile_json`,'$.mentorSchoolLocation')) AS `mentor_school_location`,json_unquote(json_extract(`users`.`profile_json`,'$.mentorClassFrequency')) AS `mentor_class_frequency`,`users`.`created_at` AS `created_at`,`users`.`updated_at` AS `updated_at` from `users` where (`users`.`role` = 'mentor');

-- 视图 mentor_trial_feedback_view
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `mentor_trial_feedback_view` AS select `mentor_trial_feedback`.`id` AS `id`,`mentor_trial_feedback`.`openid` AS `openid`,`mentor_trial_feedback`.`trial_record_id` AS `trial_record_id`,`mentor_trial_feedback`.`card_id` AS `card_id`,`mentor_trial_feedback`.`target_title` AS `target_title`,`mentor_trial_feedback`.`target_subtitle` AS `target_subtitle`,`mentor_trial_feedback`.`trial_date` AS `trial_date`,`mentor_trial_feedback`.`trial_duration` AS `trial_duration`,`mentor_trial_feedback`.`satisfaction_points_json` AS `satisfaction_points_json`,`mentor_trial_feedback`.`satisfaction_point_other` AS `satisfaction_point_other`,`mentor_trial_feedback`.`objective_unsatisfied_json` AS `objective_unsatisfied_json`,`mentor_trial_feedback`.`objective_unsatisfied_other` AS `objective_unsatisfied_other`,`mentor_trial_feedback`.`subjective_unsatisfied_json` AS `subjective_unsatisfied_json`,`mentor_trial_feedback`.`subjective_unsatisfied_other` AS `subjective_unsatisfied_other`,`mentor_trial_feedback`.`continue_choice` AS `continue_choice`,`mentor_trial_feedback`.`continue_choice_other` AS `continue_choice_other`,`mentor_trial_feedback`.`status_after_feedback` AS `status_after_feedback`,`mentor_trial_feedback`.`created_at` AS `created_at`,`mentor_trial_feedback`.`updated_at` AS `updated_at` from `mentor_trial_feedback` order by `mentor_trial_feedback`.`updated_at` desc,`mentor_trial_feedback`.`created_at` desc;

SET FOREIGN_KEY_CHECKS=1;
